name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['2.3', '2.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build project
        run: make build
        env:
          UBL_VERSION: ${{ matrix.version }}

      - name: Package
        run: make package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: url-${{ matrix.version }}
          path: target/schemas.zip
          retention-days: 7
