name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['2.3', '2.4']

    env:
      UBL_VERSION: ${{ matrix.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare version labels
        uses: k15g/action-version-labels@edge
        with:
          prefix: project

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build project
        run: make build

      - name: Package
        run: make package

      - name: Upload schemas to artifact
        uses: actions/upload-artifact@v4
        with:
          name: url-${{ matrix.version }}-json-schema
          path: target/schemas.zip
          retention-days: 7

      - name: Upload Typescript definition to artifact
        uses: actions/upload-artifact@v4
        with:
          name: url-${{ matrix.version }}-ts
          path: target/ubl.d.ts
          retention-days: 7

      - name: Upload asset [Schemas]
        uses: k15g/action-github-asset-upload@edge
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/schemas.zip
          name: ubl-${{ matrix.version }}-json-schemas-${{ env.PROJECT_VERSION }}.zip
          type: application/zip
          label: UBL ${{ matrix.version }} - JSON Schemas

      - name: Upload asset [TypeScript definitions]
        uses: k15g/action-github-asset-upload@edge
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: target/ubl.d.ts 
          name: ubl-${{ matrix.version }}-${{ env.PROJECT_VERSION }}.d.ts
          type: application/x-typescript
          label: UBL ${{ matrix.version }} - TypeScript definitions